version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-bagdex
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: bagdex
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - bagdex-network

volumes:
  mysql_data:

networks:
  bagdex-network:
    driver: bridge
